david lus onboarding
uw-midsun/strategy-onboarding pull request #30
Opened 2023-01-20 03:02 UTC by d8lu

# Strategy Onboarding

## TODO List

Onboarding tasks:

- [ ] Task 1: Implement `fibonacci_term()` in `fibonacci.py`
  - All tests in `test_fibonacci.py` should pass, run `pytest` command to check
- [ ] Task 2: Implement `find_min_index()` and `reverse_str_arr()`
  - Write tests that cover the logic that you wrote in `test_array.py`
- [ ] Task 3: Process and visualize sample data in `matplot.py`
  - Read data in CSV using `pandas` or `csv`, handle the missing values, plot using `matplotlib`
  - Include a screenshot of your graph in the PR

Some extra items:
[](url)
- [ ] Completed [strategy welcome survey](https://forms.gle/SKozF7TUn8o385zd8)

2023-01-20 19:44 UTC, d8lu commented
@rodrigotiscareno @probro27

2023-01-21 18:18 UTC, probro27 requested changes
@d8lu Everything looks fine. Just make the change suggested to get the `pytest` to run successfully. 
Thanks

2023-01-21 18:18 UTC, probro27 commented on onboarding/tests/test_array.py
> +from ..array_1 import find_min_index
This should be array not array_1. That's causing the tests to fail. Before submitting check with `pytest` if your code is working fine :)

2023-02-20 21:02 UTC, probro27 commented
Hey @d8lu any updates on the PR?

2023-05-27 06:36 UTC, closed without merging